allow-uncaught: false
async-only: false
bail: false
check-leaks: false
color: true
delay: false
diff: true
exit: false
extension:
  - mjs
forbid-only: false
forbid-pending: false
full-trace: false
global:
  - jQuery
  - $
growl: false
inline-diffs: false
recursive: false
reporter: spec
require: 'node_modules/mocha-steps'
retries: 1
slow: 1000
sort: false
spec: tests/**/*.mjs
timeout: false
trace-warnings: true
ui: bdd
v8-stack-trace-limit: 100
watch: false
watch-files:
  - 'lib/**/*.js'
  - 'tests/**/*.mjs'
